server:
  port: 8080
spring:
  # 环境 dev:开发环境|test:测试环境|prod:生产环境
  profiles:
    active: dev  #激活的配置文件

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    encoding: utf-8
    mode: HTML

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/t_contest?serverTimezone=Asia/Shanghai
    username: root
    password: 617686
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  mail:
    host: smtp.sina.cn
    port: 465
    username: hello______world@sina.cn
    password: f051385cba0d982c
    protocol: smtps
    properties.mail.smtp.ssl.enable: true
  redis:
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    #    自动生成id机制
    use-generated-keys: true
    #    驼峰命名法
    map-underscore-to-camel-case: true

mybatis-plus:
  type-enums-package: com.cqtalk.util
#logging:
#  root:
#    level: debug
#  file:
#    name: d:/work/data/nowcoder/community.log




